### ISSUE TITLE
缺少ffdec_20.1.0_nightly2789？

### ISSUE THREAD

**Issue by divineblessing** [cmy2008/doc88_extractor#1]
C:\Users\Asen\Desktop\doc88_extractor-1>python main.py
DOC88 （预览）文档提取工具
by: Cuite_Piglin
警告：你正在使用Windows系统下使用此工具，虽然我们有意使其在多平台下运行，但需要使用Cairo库才能进行pdf的转换，建议你安装GTK运行库（需要200MB左右的安装空间）：
https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases
安装后仍然无效，请尝试将安装目录下的bin目录添加到系统环境的PATH中然后重启终端或vscode
Ffdec not found! Now start downloading ffdec...
Warnning: use built download method is really really really slow, if you want, please put the ffdec files that from local(extracted ZIP format, make sure that have 'ffdecjar') to diretory 'ffdec'.
Download link: https://github.com/jindrapetrik/jpexs-decompiler/releases/download/nightly2789/ffdec_20.1.0_nightly2789.zip
Cannot create directory! Please delete it and retry.

**Comment by divineblessing** [comment]
https://github.com/jindrapetrik/jpexs-decompiler/releases  这个链接下载最新的包，解压到根目录就行了。然后修改代码，def check_ffdec():
    if not os.path.exists("ffdec/ffdec.jar"):
        print("Ffdec not found! Please make sure you have extracted ffdec files to the 'ffdec' directory.")
        exit()

    if os.system("java --version") != 0:
        print("Java not found! Please install Java and add Java to the path.")
        exit()

**Comment by cmy2008** [comment]
谢谢，已换链接

**Comment by vogala** [comment]
代码怎么改？是把def check_ffdec()中以下语句
if not os.path.exists("ffdec/ffdec.jar"):
     print("Ffdec not found! Please make sure you have extracted ffdec files to the 'ffdec' directory.")
    exit()
改成以下吗？
if os.system("java --version") != 0:
    print("Java not found! Please install Java and add Java to the path.")
    exit()
