### ISSUE TITLE
the soft can't run

### ISSUE THREAD

**Issue by vogala** [cmy2008/doc88_extractor#2]
DOC88 （预览）文档提取工具
by: Cuite_Piglin
警告：你正在使用Windows系统下使用此工具，虽然我们有意使其在多平台下运行，但需要使用Cairo库才能进行pdf的转换，建议你安装GTK运行库（需要200MB左右的安装空间）：
https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases
如果安装后仍然无效，请尝试将安装目录下的bin目录添加到系统环境的PATH中然后重启终端或vscode
Ffdec not found! Now start downloading ffdec...
Warnning: use built download method is really really really slow, if you want faster, please put the ffdec files that from yours(make sure that have 'ffdec.jar') to diretory 'ffdec'.
Download link: https://github.com/jindrapetrik/jpexs-decompiler/releases/download/version22.0.1/ffdec_22.0.1.zip
Cannot create directory! Please delete it and retry.

**Comment by vogala** [comment]
ffdec is ready

**Comment by cmy2008** [comment]
手动将ffdec的文件解压到脚本目录下的ffdec文件夹中

**Comment by cmy2008** [comment]
已更新，
